### ISSUE TITLE
PHP function calls cause errors

### ISSUE THREAD

**Issue by seweissman** [Jahia/scriptlanguages#1]
If I change the view for phpNode to the following, it works.

```
<?php
echo "This is a PHP module ! Here below we are displaying a JCR node in PHP...<br/>";
$x = 3;
$y = 5;
$z = $x + $y;
echo $z;
try {
    echo $currentNode->getProperty("phpText")->getValue()->getString();
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```

?>

But I add a call to the min function, I get an error:

```
<?php
echo "This is a PHP module ! Here below we are displaying a JCR node in PHP...<br/>";
$x = 3;
$y = 5;
$z = min($x,$y);
echo $z;
try {
    echo $currentNode->getProperty("phpText")->getValue()->getString();
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "\n";
}
```

?>

2015-05-15 16:51:24,500: ERROR [TemplateScriptFilter] - Error while rendering content
com.caucho.quercus.QuercusErrorException: eval::2: Fatal Error: 'min' is an unknown function.
    at com.caucho.quercus.env.Env.error(Env.java:6512)
    at com.caucho.quercus.env.Env.error(Env.java:6398)
    at com.caucho.quercus.env.Env.error(Env.java:6062)
    at com.caucho.quercus.expr.CallExpr.evalImpl(CallExpr.java:198)
    at com.caucho.quercus.expr.CallExpr.eval(CallExpr.java:151)
    at com.caucho.quercus.expr.Expr.evalTop(Expr.java:523)
    at com.caucho.quercus.statement.ExprStatement.execute(ExprStatement.java:67)
    at com.caucho.quercus.statement.BlockStatement.execute(BlockStatement.java:105)
    at com.caucho.quercus.program.QuercusProgram.execute(QuercusProgram.java:412)
    at com.caucho.quercus.script.QuercusScriptEngine.eval(QuercusScriptEngine.java:134)
    at org.jahia.services.render.scripting.JSR223Script.execute(JSR223Script.java:146)
    at org.jahia.services.render.filter.TemplateScriptFilter.prepare(TemplateScriptFilter.java:152)
    at org.jahia.services.render.filter.RenderChain.doFilter(RenderChain.java:183)
    at org.jahia.services.render.RenderService.render(RenderService.java:231)
    at org.jahia.taglibs.template.include.ModuleTag.render(ModuleTag.java:660)
    at org.jahia.taglibs.template.include.ModuleTag.doEndTag(ModuleTag.java:343)
    at org.apache.jsp.jmix_005flist.html.list_jsp._jspx_meth_template_module_0(org.apache.jsp.jmix_005flist.html.list_jsp:434)
    at org.apache.jsp.jmix_005flist.html.list_jsp._jspx_meth_c_forEach_0(org.apache.jsp.jmix_005flist.html.list_jsp:399)
    at org.apache.jsp.jmix_005flist.html.list_jsp._jspx_meth_c_otherwise_0(org.apache.jsp.jmix_005flist.html.list_jsp:359)
    at org.apache.jsp.jmix_005flist.html.list_jsp._jspx_meth_c_choose_0(org.apache.jsp.jmix_005flist.html.list_jsp:176)
    at org.apache.jsp.jmix_005flist.html.list_jsp._jspService(org.apache.jsp.jmix_005flist.html.list_jsp:93)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:384)
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:486)
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:380)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.jahia.bundles.extender.jahiamodules.JspServletWrapper$3.call(JspServletWrapper.java:171)
    at org.jahia.bundles.extender.jahiamodules.JspServletWrapper$3.call(JspServletWrapper.java:168)
    at org.ops4j.pax.swissbox.core.ContextClassLoaderUtils.doWithClassLoader(ContextClassLoaderUtils.java:60)
    at org.jahia.bundles.extender.jahiamodules.JspServletWrapper.service(JspServletWrapper.java:167)
    at org.apache.felix.http.base.internal.handler.ServletHandler.handleInclude(ServletHandler.java:221)
    at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:176)
    at org.apache.felix.http.base.internal.dispatch.ServletPipeline.handle(ServletPipeline.java:97)
    at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:49)
    at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
    at org.apache.felix.http.base.internal.dispatch.FilterPipeline.dispatch(FilterPipeline.java:48)
    at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:39)
    at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:67)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.felix.http.proxy.ProxyServlet.service(ProxyServlet.java:60)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
    at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:604)
    at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:543)
    at org.jahia.services.render.scripting.RequestDispatcherScript.execute(RequestDispatcherScript.java:154)
    at org.jahia.services.render.filter.TemplateScriptFilter.prepare(TemplateScriptFilter.java:152)
    at org.jahia.services.render.filter.RenderChain.doFilter(RenderChain.java:183)
    at org.jahia.services.render.RenderService.render(RenderService.java:231)
    at org.jahia.taglibs.template.include.ModuleTag.render(ModuleTag.java:660)
    at org.jahia.taglibs.template.include.AreaTag.render(AreaTag.java:433)
    at org.jahia.taglibs.template.include.ModuleTag.doEndTag(ModuleTag.java:343)
    at org.jahia.taglibs.template.include.AreaTag.doEndTag(AreaTag.java:415)

**Comment by seweissman** [comment]
This may be related to the issue described here: http://stackoverflow.com/questions/13346804/running-quercus-php-inside-java

**Comment by sergehuber** [comment]
Thanks for reporting this issue. Indeed it seems like an issue that was corrected in a more recent version of Quercus but unfortunately upgrading is not trivial because it seems they have made some changes to the API.

**Comment by seweissman** [comment]
Yes. I noticed that when I tried to use the most recent version of Quercus, the service method of QuercusServlet is now final and can't be overwritten. However, I am not longer certain that the bug linked to above is the only problem. I have been running the code through a debugger and it seems that JahiaQuercusServlet is never called at all in the current version of scriptlanguages. If I comment out all the bean definitions except for quercusScriptEngineFactory and scriptEngineFactoryInitializer, the phpNode implementation still runs with no change in the output from what I described above.

After doing a bunch of debugging, the one thing I noticed is that when the Quercus code gets loaded it is happening from JahiaTemplatePackage, and it seems that because of this the right resources are not being found. I think this might be a class loader issue, but I do not know enough about class loaders to suggest a fix.

**Comment by sergehuber** [comment]
Yes you are write the QuercusServlet is only used for initialization, we then use the JSR-223 Script engine implementation inside Jahia. 

Actually I manage to get the 4.0.39 version to deploy but it seems that no Quercus module is loaded, this is probably due to the fact that ServiceLoader mechanisms don't work well in OSGi environments. It seems they have support for Thread context class loader so maybe we need to set those up properly for the init and dispatch to work, otherwise we will need a more complex solution such as http://blog.osgi.org/2013/02/javautilserviceloader-in-osgi.html, but this could be more complex as Jahia is using Felix 4.2.1 in Jahia 7.0 which doesn't support OSGi R5 yet.

**Comment by sergehuber** [comment]
Actually after further analysis it seems that the QuercusClass and QuercusModules are loaded using ClassLoader.getResources calls. Somehow these calls don't work properly, but it is not clear why.

**Comment by sergehuber** [comment]
Ok it seems that Jahia's ChainedClassLoader implementation is not implementing the ClassLoader.getResources call which is why these resources are not being loaded properly. I have opened a ticket about this.

**Comment by sergehuber** [comment]
The Digital Factory bug is here : https://jira.jahia.org/browse/QA-7528

**Comment by seweissman** [comment]
Thanks for looking into this.
